---
#
# Playbook to install Browbeat (Rally + Shaker + PerfKitBenchmarker)
#

- hosts: tester
  vars_files:
    - vars/all.yml
  remote_user: "{{ browbeat_user }}"
  roles:
    - common
    - browbeat
    - stockpile
    - { role: browbeat-results, when: browbeat_results_in_httpd}
    - firewall
    - rally
    - shaker
    - { role: flavors, when: browbeat_create_flavors}
    - { role: images, when: browbeat_upload_guest_images}
    - { role: workloads, when: install_browbeat_workloads}
  environment: "{{proxy_env}}"
